name: Build SageAttention

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag
        required: true
        type: string
        default: main
      torch_minor:
        description: PyTorch minor version
        required: true
        type: string
        default: '7'
      torch_patch:
        description: PyTorch patch version
        required: true
        type: string
        default: '1'
      torch_is_nightly:
        description: PyTorch is nightly
        required: true
        type: string
        default: '0'
      cuda_major:
        description: CUDA major version
        required: true
        type: string
        default: '12'
      cuda_minor:
        description: CUDA minor version
        required: true
        type: string
        default: '8'
      cuda_patch:
        description: CUDA patch version
        required: true
        type: string
        default: '1'
      extra_cuda_arch:
        description: Extra CUDA arch
        required: false
        type: string
        default: ''
      extra_wheel_version_suffix:
        description: Extra wheel version suffix
        required: false
        type: string
        default: ''
      is_python_abi3:
        description: Is Python ABI3
        required: false
        type: boolean
        default: false

jobs:
  resolve-ref:
    runs-on: windows-latest
    permissions:
      contents: read
    outputs:
      commit_sha: ${{ steps.resolve.outputs.commit_sha }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.git_tag }}
          path: SageAttention

      - id: resolve
        shell: powershell
        run: |
          cd SageAttention
          "commit_sha=$(git rev-parse HEAD)" >> $Env:GITHUB_OUTPUT

  build-sageattn:
    name: Build ${{ inputs.git_tag }} @ ${{ needs.resolve-ref.outputs.commit_sha }}
    needs: resolve-ref
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - name: Configure Git
        shell: powershell
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v6
        with:
          ref: ${{ needs.resolve-ref.outputs.commit_sha }}
          path: SageAttention

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - uses: Jimver/cuda-toolkit@v0.2.35
        with:
          cuda: ${{ inputs.cuda_major }}.${{ inputs.cuda_minor }}.${{ inputs.cuda_patch }}
          use-github-cache: false

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build wheels
        shell: powershell
        env:
          CUDA_MAJOR_VERSION: ${{ inputs.cuda_major }}
          CUDA_MINOR_VERSION: ${{ inputs.cuda_minor }}
          CUDA_PATCH_VERSION: ${{ inputs.cuda_patch }}
          TORCH_MINOR_VERSION: ${{ inputs.torch_minor }}
          TORCH_PATCH_VERSION: ${{ inputs.torch_patch }}
          TORCH_IS_NIGHTLY: ${{ inputs.torch_is_nightly }}
          EXTRA_CUDA_ARCH: ${{ inputs.extra_cuda_arch }}
          EXTRA_WHEEL_VERSION_SUFFIX: ${{ inputs.extra_wheel_version_suffix }}
          IS_PYTHON_ABI3: ${{ inputs.is_python_abi3 }}
        run: |
          # Get-ChildItem Env:
          # (Get-WmiObject Win32_Processor).Name
          # (Get-WmiObject Win32_PhysicalMemory | Measure-Object -Property Capacity -Sum).Sum / 1GB
          # (Get-WmiObject Win32_VideoController).Name

          # Get-Command -All python
          # python --version
          python -m pip install --upgrade pip
          pip install --upgrade cibuildwheel simpleindex

          cd SageAttention
          git rev-parse HEAD

          $CudaVersion = [version]("{0}.{1}.{2}" -f $Env:CUDA_MAJOR_VERSION, $Env:CUDA_MINOR_VERSION, $Env:CUDA_PATCH_VERSION)
          $TorchVersion = [version]("2.{0}.{1}" -f $Env:TORCH_MINOR_VERSION, $Env:TORCH_PATCH_VERSION)

          python update_pyproject.py

          Start-Process -NoNewWindow simpleindex simpleindex.toml
          $Env:PIP_INDEX_URL = "http://127.0.0.1:8000"

          $Env:DISTUTILS_USE_SDK = "1"

          $Env:TORCH_CUDA_ARCH_LIST = "8.0 8.6 8.9 9.0 "
          if ($CudaVersion -ge [version]"12.8")
          {
            $Env:TORCH_CUDA_ARCH_LIST += "12.0 "
          }
          $Env:TORCH_CUDA_ARCH_LIST += $Env:EXTRA_CUDA_ARCH

          $Env:SAGEATTENTION_WHEEL_VERSION_SUFFIX = "+cu{0}{1}torch2.{2}.{3}" -f $Env:CUDA_MAJOR_VERSION, $Env:CUDA_MINOR_VERSION, $Env:TORCH_MINOR_VERSION, $Env:TORCH_PATCH_VERSION
          $Env:SAGEATTENTION_WHEEL_VERSION_SUFFIX += $Env:EXTRA_WHEEL_VERSION_SUFFIX

          if ($Env:IS_PYTHON_ABI3 -eq "true")
          {
            $Env:CIBW_BUILD = "{cp310-win_amd64,}"
          }
          else
          {
            if ($TorchVersion -ge [version]"2.9")
            {
              $Env:CIBW_BUILD = "{cp310-win_amd64,cp311-win_amd64,cp312-win_amd64,cp313-win_amd64,cp314-win_amd64}"
            }
            elseif ($TorchVersion -ge [version]"2.6")
            {
              $Env:CIBW_BUILD = "{cp39-win_amd64,cp310-win_amd64,cp311-win_amd64,cp312-win_amd64,cp313-win_amd64}"
            }
            else
            {
              $Env:CIBW_BUILD = "{cp39-win_amd64,cp310-win_amd64,cp311-win_amd64,cp312-win_amd64}"
            }
          }

          $Env:CIBW_BUILD_VERBOSITY = "1"
          # Sometimes torch may conflict with cibuildwheel's pinned dependency versions
          # $Env:CIBW_DEPENDENCY_VERSIONS = "latest"
          cibuildwheel .

      - uses: actions/attest@v4
        with:
          subject-path: SageAttention/wheelhouse/*.whl

      # Currently actions/upload-artifact only supports uploading one file at a time when archive is disabled
      - uses: actions/upload-artifact@v7
        if: ${{ inputs.is_python_abi3 }}
        with:
          path: SageAttention/wheelhouse/*.whl
          archive: false

      - uses: actions/upload-artifact@v7
        if: ${{ !inputs.is_python_abi3 && fromJSON(inputs.torch_minor) < 9 }}
        with:
          path: SageAttention/wheelhouse/*-cp39-cp39-win_amd64.whl
          archive: false

      - uses: actions/upload-artifact@v7
        if: ${{ !inputs.is_python_abi3 }}
        with:
          path: SageAttention/wheelhouse/*-cp310-cp310-win_amd64.whl
          archive: false

      - uses: actions/upload-artifact@v7
        if: ${{ !inputs.is_python_abi3 }}
        with:
          path: SageAttention/wheelhouse/*-cp311-cp311-win_amd64.whl
          archive: false

      - uses: actions/upload-artifact@v7
        if: ${{ !inputs.is_python_abi3 }}
        with:
          path: SageAttention/wheelhouse/*-cp312-cp312-win_amd64.whl
          archive: false

      - uses: actions/upload-artifact@v7
        if: ${{ !inputs.is_python_abi3 && fromJSON(inputs.torch_minor) >= 6 }}
        with:
          path: SageAttention/wheelhouse/*-cp313-cp313-win_amd64.whl
          archive: false

      - uses: actions/upload-artifact@v7
        if: ${{ !inputs.is_python_abi3 && fromJSON(inputs.torch_minor) >= 9 }}
        with:
          path: SageAttention/wheelhouse/*-cp314-cp314-win_amd64.whl
          archive: false
