name: Build SageAttention

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag
        required: true
        type: string
        default: main
      torch_minor:
        description: PyTorch minor version
        required: true
        type: string
        default: '7'
      torch_patch:
        description: PyTorch patch version
        required: true
        type: string
        default: '1'
      torch_is_nightly:
        description: PyTorch is nightly
        required: true
        type: string
        default: '0'
      cuda_minor:
        description: CUDA minor version
        required: true
        type: string
        default: '8'
      cuda_patch:
        description: CUDA patch version
        required: true
        type: string
        default: '1'

jobs:
  build-sageattn:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: Jimver/cuda-toolkit@v0.2.22
        with:
          cuda: 12.${{ inputs.cuda_minor }}.${{ inputs.cuda_patch }}
          use-github-cache: false
          use-local-cache: false

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build wheel
        shell: powershell
        run: |
          # Get-ChildItem Env:
          # (Get-WmiObject Win32_Processor).Name
          # (Get-WmiObject Win32_PhysicalMemory | Measure-Object -Property Capacity -Sum).Sum / 1GB
          # (Get-WmiObject Win32_VideoController).Name

          # Get-Command -All python
          # python --version
          python -m pip install --upgrade pip
          pip install --upgrade cibuildwheel simpleindex

          git config --global core.autocrlf false
          git clone --branch ${{ inputs.git_tag }} --depth 1 https://github.com/woct0rdho/SageAttention.git
          cd SageAttention
          git rev-parse HEAD

          $Env:CUDA_MINOR_VERSION = "${{ inputs.cuda_minor }}"
          $Env:TORCH_MINOR_VERSION = "${{ inputs.torch_minor }}"
          $Env:TORCH_PATCH_VERSION = "${{ inputs.torch_patch }}"
          $Env:TORCH_IS_NIGHTLY = "${{ inputs.torch_is_nightly }}"
          python update_pyproject.py

          Start-Process -NoNewWindow simpleindex simpleindex.toml
          $Env:PIP_INDEX_URL = "http://127.0.0.1:8000"

          $Env:DISTUTILS_USE_SDK = "1"
          if ($Env:CUDA_MINOR_VERSION -gt "6")
          {
            $Env:SAGEATTENTION_CUDA_ARCH_LIST = "8.0 8.6 8.9 9.0 12.0"
          }
          else
          {
            $Env:SAGEATTENTION_CUDA_ARCH_LIST = "8.0 8.6 8.9 9.0"
          }
          $Env:SAGEATTENTION_WHEEL_VERSION_SUFFIX = "+cu12${{ inputs.cuda_minor }}torch2.${{ inputs.torch_minor }}.${{ inputs.torch_patch }}"
          if ($Env:TORCH_MINOR_VERSION -gt "5")
          {
            $Env:CIBW_BUILD = "{cp39-win_amd64,cp310-win_amd64,cp311-win_amd64,cp312-win_amd64,cp313-win_amd64}"
          }
          else
          {
            $Env:CIBW_BUILD = "{cp39-win_amd64,cp310-win_amd64,cp311-win_amd64,cp312-win_amd64}"
          }
          $Env:CIBW_BUILD_VERBOSITY = "1"
          # torch may conflict with cibuildwheel's pinned dependency versions
          $Env:CIBW_DEPENDENCY_VERSIONS = "latest"
          cibuildwheel .

      - uses: actions/upload-artifact@v4
        with:
          path: SageAttention/wheelhouse/*
